// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQKL7vpcM8ysMpPf8SeKKb5LoMBOb64NI',
    appId: '1:885245552484:web:3553b264b31eff99eebc71',
    messagingSenderId: '885245552484',
    projectId: 'video-calling-app-3468d',
    authDomain: 'video-calling-app-3468d.firebaseapp.com',
    storageBucket: 'video-calling-app-3468d.firebasestorage.app',
    measurementId: 'G-G5CTV8CV04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu8Crc1SrCB3PGxHFtE-vK6y14yYxs34s',
    appId: '1:885245552484:android:83c743d38fb8173aeebc71',
    messagingSenderId: '885245552484',
    projectId: 'video-calling-app-3468d',
    storageBucket: 'video-calling-app-3468d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNfuLHtEp877_OOvBxHR-ecQbkUMCpxiI',
    appId: '1:885245552484:ios:a192a7fb503fb19feebc71',
    messagingSenderId: '885245552484',
    projectId: 'video-calling-app-3468d',
    storageBucket: 'video-calling-app-3468d.firebasestorage.app',
    iosBundleId: 'com.example.videoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNfuLHtEp877_OOvBxHR-ecQbkUMCpxiI',
    appId: '1:885245552484:ios:a192a7fb503fb19feebc71',
    messagingSenderId: '885245552484',
    projectId: 'video-calling-app-3468d',
    storageBucket: 'video-calling-app-3468d.firebasestorage.app',
    iosBundleId: 'com.example.videoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQKL7vpcM8ysMpPf8SeKKb5LoMBOb64NI',
    appId: '1:885245552484:web:9d89ae380b8d300aeebc71',
    messagingSenderId: '885245552484',
    projectId: 'video-calling-app-3468d',
    authDomain: 'video-calling-app-3468d.firebaseapp.com',
    storageBucket: 'video-calling-app-3468d.firebasestorage.app',
    measurementId: 'G-6R3NYE2MVG',
  );
}
